# these are the params we use for 106A Lab 4
/**:
    ros__parameters:
      video_device: "/dev/video0"
      framerate: 30.0
      io_method: "mmap"
      camera_name: "camera1"
      frame_id: "camera1"
      pixel_format: "yuyv"  # see usb_cam/supported_formats for list of supported formats
      camera_info_url: "package://usb_cam/config/c922_pro_stream_webcam.yaml"
      image_width: 1280
      image_height: 720
      # brightness: -1
      # contrast: -1
      # saturation: -1
      # sharpness: -1
      # gain: -1
      # auto_white_balance: true
      # white_balance: 4000
      # autoexposure: true
      # exposure: 100
      # autofocus: false
      # focus: -1